from sqlalchemy import Column, Integer, String, Boolean, ForeignKey, Numeric, Text, Date, DateTime, JSON
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
from .database import Base
import uuid
import random
import string


def _new_id():
    return str(uuid.uuid4())


def generate_registration_code():
    """Generate a unique 8-character alphanumeric registration code."""
    return ''.join(random.choices(string.ascii_uppercase + string.digits, k=8))


class User(Base):
    __tablename__ = "users"
    id = Column(String, primary_key=True, default=_new_id)
    email = Column(String, unique=True, index=True)
    hashed_password = Column(String)
    full_name = Column(String)
    role = Column(String, default="locataire")  # admin, gestionnaire, proprietaire, locataire
    phone = Column(String)
    is_active = Column(Boolean, default=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    last_login = Column(DateTime(timezone=True))

    profile = relationship("Profile", back_populates="user", uselist=False)
    proprietaire = relationship("Proprietaire", back_populates="user", uselist=False)
    locataire = relationship("Locataire", back_populates="user", uselist=False)


class Profile(Base):
    __tablename__ = "profiles"
    id = Column(String, ForeignKey("users.id", ondelete="CASCADE"), primary_key=True)
    full_name = Column(String)
    phone = Column(String)
    role = Column(String)
    adresse = Column(String)
    date_naissance = Column(Date)
    nationalite = Column(String)
    piece_identite_type = Column(String)
    piece_identite_numero = Column(String)
    statut_dossier = Column(String, default="en_attente")
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())

    user = relationship("User", back_populates="profile")


class Proprietaire(Base):
    __tablename__ = "proprietaires"
    id = Column(String, primary_key=True, default=_new_id)
    user_id = Column(String, ForeignKey("users.id", ondelete="CASCADE"), unique=True)
    type_proprietaire = Column(String, default="particulier")
    nom_entreprise = Column(String)
    est_actif = Column(Boolean, default=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())

    user = relationship("User", back_populates="proprietaire")
    proprietes = relationship("Propriete", back_populates="proprietaire")


class Locataire(Base):
    __tablename__ = "locataires"
    id = Column(String, primary_key=True, default=_new_id)
    user_id = Column(String, ForeignKey("users.id", ondelete="CASCADE"), unique=True)
    profession = Column(String)
    employeur = Column(String)
    revenu_mensuel = Column(Numeric)
    est_actif = Column(Boolean, default=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())

    user = relationship("User", back_populates="locataire")


class CodeInscription(Base):
    """Registration codes generated by admin for proprietaires/locataires."""
    __tablename__ = "codes_inscription"
    id = Column(String, primary_key=True, default=_new_id)
    code = Column(String(12), unique=True, index=True)
    role = Column(String)  # proprietaire or locataire
    nom_beneficiaire = Column(String)
    email_beneficiaire = Column(String)
    est_utilise = Column(Boolean, default=False)
    user_id = Column(String, ForeignKey("users.id", ondelete="SET NULL"), nullable=True)
    contrat_id = Column(String, nullable=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())


class Contrat(Base):
    __tablename__ = "contrats"
    id = Column(String, primary_key=True, default=_new_id)
    reference = Column(String, unique=True)
    propriete_id = Column(String, ForeignKey("proprietes.id"), nullable=True)
    proprietaire_id = Column(String, ForeignKey("proprietaires.id"), nullable=True)
    locataire_id = Column(String, ForeignKey("locataires.id"), nullable=True)
    # Info before registration happens
    nom_proprietaire = Column(String)
    email_proprietaire = Column(String)
    nom_locataire = Column(String)
    email_locataire = Column(String)
    # Registration codes
    code_proprietaire_id = Column(String, ForeignKey("codes_inscription.id"), nullable=True)
    code_locataire_id = Column(String, ForeignKey("codes_inscription.id"), nullable=True)
    # Financial
    loyer_mensuel = Column(Numeric)
    devise = Column(String, default="HTG")
    caution = Column(Numeric, default=0)
    # Dates
    date_debut = Column(Date)
    date_fin = Column(Date)
    statut = Column(String, default="actif")  # actif, expire, resilie
    notes = Column(Text)
    created_by = Column(String, ForeignKey("users.id"))
    created_at = Column(DateTime(timezone=True), server_default=func.now())

    propriete = relationship("Propriete", foreign_keys=[propriete_id])
    code_proprietaire = relationship("CodeInscription", foreign_keys=[code_proprietaire_id])
    code_locataire = relationship("CodeInscription", foreign_keys=[code_locataire_id])


class Zone(Base):
    __tablename__ = "zones"
    id = Column(String, primary_key=True, default=_new_id)
    nom = Column(String, nullable=False)
    slug = Column(String, unique=True)
    description = Column(Text)
    actif = Column(Boolean, default=True)
    ordre = Column(Integer, default=0)


class Agent(Base):
    __tablename__ = "agents"
    id = Column(String, primary_key=True, default=_new_id)
    nom = Column(String, nullable=False)
    prenom = Column(String, nullable=False)
    titre = Column(String)
    email = Column(String)
    telephone = Column(String)
    whatsapp = Column(String)
    photo_url = Column(String)


class Propriete(Base):
    __tablename__ = "proprietes"
    id = Column(String, primary_key=True, default=_new_id)
    reference = Column(String, unique=True)
    slug = Column(String, unique=True)
    titre = Column(String, nullable=False)
    description = Column(Text)
    type_bien = Column(String)
    type_transaction = Column(String)
    prix = Column(Numeric, nullable=False, default=0)
    devise = Column(String, default="USD")
    adresse = Column(String)
    ville = Column(String, default="Pétion-Ville")
    zone_id = Column(String, ForeignKey("zones.id"))
    nb_chambres = Column(Integer, default=0)
    nb_salles_bain = Column(Integer, default=0)
    superficie_m2 = Column(Numeric, default=0)
    statut_bien = Column(String, default="disponible")
    est_actif = Column(Boolean, default=True)
    est_vedette = Column(Boolean, default=False)
    images = Column(JSON, default=list)
    proprietaire_id = Column(String, ForeignKey("proprietaires.id"), nullable=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())

    zone = relationship("Zone")
    proprietaire = relationship("Proprietaire", back_populates="proprietes")


class Paiement(Base):
    __tablename__ = "paiements"
    id = Column(String, primary_key=True, default=_new_id)
    contrat_id = Column(String, ForeignKey("contrats.id"), nullable=True)
    montant = Column(Numeric)
    devise = Column(String, default="HTG")
    date_paiement = Column(Date)
    date_echeance = Column(Date)
    statut = Column(String, default="en_attente")  # en_attente, paye, en_retard
    notes = Column(Text)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
